const EDIT_ALBUM = 4;
const RESET_ALBUM = 5;
const SET_LOADING = 6;
const FETCH_COMPLETE = 7;
const HANDLE_INPUT_CHANGE = 8;
const SUBMIT_COMPLETE = 10;

export {
    SUBMIT_COMPLETE,
    EDIT_ALBUM,
    RESET_ALBUM,
    SET_LOADING,
    FETCH_COMPLETE,
    HANDLE_INPUT_CHANGE,
};
