const EDIT_GENRE = 4;
const RESET_GENRE = 5;
const SET_LOADING = 6;
const FETCH_COMPLETE = 7;
const HANDLE_INPUT_CHANGE = 8;
const SUBMIT_COMPLETE = 10;

export {
    SUBMIT_COMPLETE,
    EDIT_GENRE,
    RESET_GENRE,
    SET_LOADING,
    FETCH_COMPLETE,
    HANDLE_INPUT_CHANGE,
};
